export enum USER_ROLES {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  CANDIDATE = 'CANDIDATE',
  EMPLOYEE = 'EMPLOYEE',
}

export enum JOB_LEVEL {
  LEVEL_A = "LEVEL-A",
  LEVEL_B = "LEVEL-B",
  LEVEL_C = "LEVEL-C",
  LEVEL_D = "LEVEL-D",
  LEVEL_E = "LEVEL-E",
  LEVEL_F = "LEVEL-F"
}

export enum USER_BADGE {
  PERFORMANCE_READINESS_CREDENTIAL = "PERFORMANCE READINESS CREDENTIAL",
  RELIABILITY = "RELIABILITY",
  SAFETY_CONSCIOUS = "SAFETY-CONSCIOUS",
  GROWTH_MINDSET = "GROWTH MINDSET"
}

export enum ASSESSMENT_STATUS {
  PENDING = "pending",
  COMPLETED = "completed",
  CANCELLED = "cancelled",
  LINK_SENT = "link_sent",
  APPROVED = "approved",
  REJECTED = "rejected"
}


export enum ASSESSMENT_BADGE {
  BRONZE = "BRONZE",
  SILVER = "SILVER",
  GOLD = "GOLD"
}